project:
  type: website
  #resources: data
  resources:
    - "docs/*.R"
    - "data/*.*"

website:
  navbar:
    left:
      #      - href: index.qmd
      #        text: Home
      #      - about.qmd
      - text: "Índice"
        href: index.html
      - text: "Datos"
        href: Datos.html
      - text: "Contenidos"
        href: Contenidos.html
      - text: "Evaluación"
        href: Evaluacion.html
      - text: "Proyecto Final"
        href: ProyectoFinal.html
#     - text: "Otro con submenus"
#       menu:
#         - text: "Create a Project"
#           href: project.html
#         - text: "Set Build Options"
#           href: build.html
#         - text: "Create a _site.yml"
#           href: create_yml.html
#     - text: "Add Features"
#       menu:
#         - text: "Tables and Plots"
#           href: tables_plots.html
#         - text: "Include Images"
#           href: images.html
#         - text: "Embed a webpage"
#           href: embed.html
#     - text: "Publish and Update"
#       menu:
#         - text: "Publishing"
#           href: publishing.html
#         - text: "Updating"
#           href: updating.html

format:
  html:
    theme: zephyr # materia # readable # cerulean # pulse # spacelab # litera #
    css: styles.css
    toc: true
