---
title: "Tema 06 - Selección y Regularización "
subtitle: "Ejercicio Práctico 1"
author:
    - "Pedro Albarrán"
    - "Alberto Pérez"
institute: "Dpto. de Fundamentos del Análisis Económico. Universidad de Alicante"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 3
    theme: cosmo
    css: styles.css
execute:
  enabled: true
  eval: false
  echo: true
  warning: false
  message: false
  output: false
  fig.show: hide
lang: es
strip-comments: true
---
<!-- markdownlint-disable-file MD013 -->

```{r}
#| label: setup
#| include: false
#| eval: true
# se evalua pero no incluye output (mensajes, etc.)

# Elimino todo del Entorno (del documento)
rm(list = ls())

# Working directory
#setwd("/home/albarran/Dropbox/MAD/00.TEC")

# Cargo todas las bibliotecas necesarias
# (se podría hacer cuando cada una sea necesaria)
library(tidyverse)
library(rio)
library(kableExtra)
```


## Ejercicio

En este ejercicio volvemos a considerar <!-- los apartados 2 y 3 --> el apartado 2 del Ejercicio 1 del Tema 5. Utilizaremos **todas las observaciones** de la muestra para ajustar los modelos de regresión lineal con regularización LASSO y *Ridge regression* usando `glmnet`.

<!-- Vuestro documento final deberá incluir para **cada apartado**: -->

En vuestro documento final deberá:

  1. Explicar brevemente cómo se selecciona el mejor modelo de LASSO y de *Ridge regression*, mostrando los códigos, tablas y/o gráficos que consideréis necesarios.
  
  2. Partiendo de la tabla obtenida en el Tema 5, añadir una columna con los resultados de la estimación mediante el mejor modelo de LASSO y de *Ridge regression*. Comentar **brevemente** las diferencias entre los modelos y las implicaciones.
  
  3. ¿Qué modelo es mejor para predecir el número de visitantes?
  
  4. La comisión gestora quiere saber el impacto de un incremento de la temperatura sobre el número de visitantes. Usando informes científicos sobre el calentamiento global, se sabe que la temperatura media aumentará 5º Fahrenheit en verano y 3º Fahrenheit en invierno. ¿Qué cambios se espera que ocurran en el número de visitantes debido al calentamiento global?

## Entrega

Rellenad este
[FORMULARIO](https://docs.google.com/forms/d/e/1FAIpQLSdJW0ss-IT9K_19HvFMXF14feSL5g-j480NDmBTfNgX5i2myQ/viewform) con vuestros datos y subid


  - vuestro archivo de .qmd

  - el resultado de renderizarlo: bien un archivo autocontenido .html (o .pdf o .docx) o bien un archivo .html y el directorio relacionado con el mismo nombre; en ambos casos, se recomienda comprimir todo para enviarlo.


IMPORTANTE: el nombre de los ficheros que subáis DEBE seguir el siguiente formato que incluye vuestro número de DNI: ej.,

  * Tema06ej1_123456789.qmd

  * Tema06ej1_123456789.zip
